### ISSUE TITLE
Migration to WebAssembly/wasi-libc

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wasi-libc#147]
A while back we decided to go ahead with the long planned move to https://github.com/WebAssembly/wasi-libc.

What is that current status?   Can you use github's "move/migrate" feature to enable old users to be seemlessly redirected?

(Is there any tracking bug for this somewhere?  If so, sorry for the noise).

**Comment by sunfishcode** [comment]
The current status is that we're waiting until we figure out the plan for handling the licenses before making the actual move. I do hope to migrate the repo to preserve all the history and users.

**Comment by sunfishcode** [comment]
It's now done; the wasi-libc repo has moved into the WebAssembly organization! The repository was transferred, so users will be seamlessly redirected, and history, issues, PRs, etc. are preserved.
