### ISSUE TITLE
trunc.c should be specialised for wasm32

### ISSUE THREAD

**Issue by ggreif** [WebAssembly/wasi-libc#190]
Suggesting `libc-top-half/musl/src/math/wasm32/trunc.c` which (analogously to the other architectures) would use the `ftrunc` WASM instruction.

Similarly for the other available _funop_ and _fbinop_ intrinsics.

**Comment by sunfishcode** [comment]
The C `trunc` function rounds to nearest with ties toward zero. The wasm `trunc` instruction rounds towards zero. The wasm `nearest` instructions round to nearest with ties to even. So while it's possible there's an optimized sequence which computes the C `trunc` function in wasm, it would need to be more than a single instruction.

Unless something is overlooked, all C functions which can be mapped to a single wasm function are [mapped](https://github.com/WebAssembly/wasi-libc/blob/master/basics/sources/math/math-builtins.c). Clang also performs this optimization inline.

**Comment by sunfishcode** [comment]
Oops, I mixed up a few different things there. `trunc` is already mapped; we don't use the musl version, but use [this version](https://github.com/WebAssembly/wasi-libc/blob/master/basics/sources/math/math-builtins.c) instead.

**Comment by sunfishcode** [comment]
Consequently, this is fixed!
