### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by pchickey** [WebAssembly/wasi-libc#205]
The WASI subgroup is changing the default branch names in all repositories to `main`.

Please consider this a tracking issue. It is not intended for public debate.

* [x] Change branch name
* [x] Update CI
* [x] Update build scripts
* [x] Update documentation

**Comment by sunfishcode** [comment]
Github how as an update [here](https://github.com/github/renaming#renaming-the-default-branch-from-master). They will be "investing in tools to make renaming the default branch of an existing repository a seamless experience for both maintainers and contributors", so it sounds like we should wait for now and see what they come up with.

**Comment by pchickey** [comment]
The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by pchickey** [comment]
AFAICT, no CI, build scripts, or documentation changes were required in this repo.
