### ISSUE TITLE
Activate the use of `__heap_base`

### ISSUE THREAD

**Issue by michaelvoronov** [WebAssembly/wasi-libc#212]
Seems that https://bugs.llvm.org/show_bug.cgi?id=43613 fixed, what about activating `__heap_base` disabled by https://github.com/WebAssembly/wasi-libc/pull/132 ?

**Comment by sbc100** [comment]
I suppose it depends on what level of compatibility we want in clang.  At the very least we could perhaps use a clang version check here?

**Comment by sbc100** [comment]
Oh I guess this made it into llvm 9, and I don't think we need to continue to support llvm 8 now that 10 is stable, so I guess you are correct and we should re-enable it.

**Comment by michaelvoronov** [comment]
I can resurrect the old PR with `__heap_base`.

**Comment by sunfishcode** [comment]
I agree; I think it's fine to drop support for LLVM 8 for building WASI libc.
