### ISSUE TITLE
_Static_assert disable 

### ISSUE THREAD

**Issue by DiachenkoIgor** [WebAssembly/wasi-libc#223]
I try to run code analyzer for pre-processed (with emcc) C file and I receive error that "_Static_assert" is unknown. I run emcc pre-processor with parameter '-std=c99'. Why doesn't this keyword remove?

**Comment by sbc100** [comment]
`_Static_assert` did not exist in c99.  It looks like it was added in C11: 
 https://en.cppreference.com/w/c/language/_Static_assert.

If you are using emcc then you should probably file bugs on the emscripten repo.

**Comment by sunfishcode** [comment]
Also, if you want to preprocess WASI libc's headers, you can use `clang --target=wasm32-wasi -E`.

And, the preprocessor doesn't remove `_Static_assert`; it's just recognized as a keyword by the compiler. If you have a static analysis tool which doesn't recognize `_Static_assert`, you may be able to work around the problem by defining `-D_Static_assert(x, msg)=` and ignoring warnings about semicolons.

**Comment by DiachenkoIgor** [comment]
Thank you for reply. It helped.
