### ISSUE TITLE
error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]

### ISSUE THREAD

**Issue by expnkx** [WebAssembly/wasi-libc#245]
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
1 error generated.
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/cbrtl.c:18:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/fabsl.o] Error 1
1 error generated.
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/atan2l.c:18:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/tanhf.c:1:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/log.c:10:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
1 error generated.
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/tgamma.c:25:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/__cosdf.c:17:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/cbrtl.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/atan2l.o] Error 1
1 error generated.
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/__cosdf.o] Error 1
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/tanhf.o] Error 1
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/__tan.c:46:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/tgamma.o] Error 1
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/ilogbf.c:2:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
make[1]: *** [Makefile:378: /home/cqwrteur/wasi-sdk/src/wasi-libc/build/libc-top-half/musl/src/math/log.o] Error 1
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/nexttoward.c:1:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;
                             ^
1 error generated.
1 error generated.
1 error generated.
In file included from /home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/math/round.c:1:
/home/cqwrteur/wasi-sdk/src/wasi-libc/libc-top-half/musl/src/internal/libm.h:179:23: error: variable 'y' set but not used [-Werror,-Wunused-but-set-variable]
        volatile long double y;

**Comment by pchickey** [comment]
Thanks for the report. Wasi-libc inherits that code from the musl libc project.

That error is coming from the following definition:
```
static inline void fp_force_evall(long double x)
{
	volatile long double y;
	y = x;
}
```
That definition is the same upstream (musl 1.2.2). Is this known to be a bug upstream? If not, would you mind reporting it there?

**Comment by sbc100** [comment]
I don't think want to make it our goal to fix all these kind of warning in upstream musl code.

Thats why our Makefile has this section:

```
CFLAGS += -Wall -Wextra -Werror \                                                
  -Wno-null-pointer-arithmetic \                                                 
  -Wno-unused-parameter \                                                           
  -Wno-sign-compare \                                                            
  -Wno-nused-variable \                                                                     
  -Wno-unused-function \                                                         
  -Wno-ignored-attributes \                                                      
  -Wno-missing-braces \                                                          
  -Wno-ignored-pragmas   
```

If new versions clang need `-Wno-unused-but-set-variable` in addition to ` -Wno-nused-variable` then we should just add that.
