### ISSUE TITLE
Use WebAssembly bulk memory opcodes for memcpy/memset?

### ISSUE THREAD

**Issue by TerrorJack** [WebAssembly/wasi-libc#262]
WebAssembly bulk memory opcodes have shipped for major browsers for some time. Does it make sense to use that for `memcpy`/`memset` functions in `wasi-libc`? If there are no objections in principle, I'd like to try opening a PR for this.

**Comment by sunfishcode** [comment]
That sounds great!

It appears bulk-memory is supported in all the engines tracked in [the roadmap](https://webassembly.org/roadmap/), and according to [this](https://github.com/WebAssembly/proposals/blob/main/finished-proposals.md) bulk memory was standardized in February.

Could you write the code guarded with `#ifdef __wasm_bulk_memory__`? I expect we'll enable it by default, but that way if someone wants to make a custom build of wasi-libc without it, they can pass -mno-bulk-memory to clang and build their own.

**Comment by kripken** [comment]
I'd recommend measuring the effect of this. At least at some point it was the case that not all browsers optimized these operations  very well. (But it is a win for size, of course.)
