### ISSUE TITLE
Adding Support for `sock_accept()` to `wasi-libc`

### ISSUE THREAD

**Issue by Deepansharora27** [WebAssembly/wasi-libc#267]

**Comment by Deepansharora27** [comment]
Hi 
I am Deepanshu and have been contributing as an Intern to the Enarx Project for the last 4-5 months. 
Recently, I was brainstorming on some ideas and that's when I came across this issue in the Enarx Repository.

I would be highly interested in adding the Support for `sock_accept()` to `wasi-libc`.
The Only Roadblock I have is since I am new to this repository if anyone could point me in a possible direction where I could research more about this and then I can come up with a tangible roadmap of adding the support. 

Thanks!

**Comment by TerrorJack** [comment]
Hi, I believe you can

- Update the `WASI` submodule to latest `main`
- Set up the rust toolchain, and run `cargo run -- generate-libc` in `tools/wasi-headers` directory, to add `sock_accept` in the headers
- Build `wasi-libc`, fix the errors by adjusting `expected` content

That should be sufficient to add `__wasi_sock_accept` function. Then the next step is patching musl sources related to sockets to actually use it.

**Comment by Deepansharora27** [comment]
Hi @TerrorJack 
Thanks a lot  for helping out on this 
I will work on this and will get back to you here in case of any blockers.

**Comment by lum1n0us** [comment]
A reference here

[wasi_socket_ext.h](https://github.com/bytecodealliance/wasm-micro-runtime/blob/dev/socket_api/core/iwasm/libraries/lib-socket/inc/wasi_socket_ext.h) and [wasi_socket_ext.c](https://github.com/bytecodealliance/wasm-micro-runtime/blob/dev/socket_api/core/iwasm/libraries/lib-socket/src/wasi/wasi_socket_ext.c)

**Comment by Deepansharora27** [comment]
@TerrorJack Hi 
I have followed the first two steps as you suggested and I am able to execute them on my System.

But can you elaborate on the third point
Fixing the errors by adjusting the `expected` content.

**Comment by TerrorJack** [comment]
> Build wasi-libc, fix the errors by adjusting expected content

Enable github actions in your fork, do a push and look at the build error.
