### ISSUE TITLE
Adding `IFTODT` for more compatibility

### ISSUE THREAD

**Issue by kateinoigakukun** [WebAssembly/wasi-libc#268]
Currently `IFTODT` is not defined in wasi-libc, even though `DT_XXX` family are defined.

https://github.com/WebAssembly/wasi-libc/blob/ad5133410f66b93a2381db5b542aad5e0964db96/libc-top-half/musl/include/dirent.h#L50-L65

On the ruby side, we faced a compatibility issue due to missing `IFTODT` https://github.com/ruby/ruby/pull/5614 because we assume `IFTODT` is always defined when `DT_UNKNOWN` is defined, and other platforms are compatible with this.

Do you think it would be worth adding `IFTODT`?

**Comment by sunfishcode** [comment]
Yes, it looks like we should add a `IFTODT`.
