### ISSUE TITLE
Confusion around SIGCHLD value?

### ISSUE THREAD

**Issue by dkegel-fastly** [WebAssembly/wasi-libc#271]
What's the right value to use for SIGCHLD in a wasi app... 16 or 17?  

```
$ find . -type f -print0 | xargs -0 grep CHLD | egrep 'wasm|wasi'
./libc-top-half/musl/arch/wasm32/bits/signal.h:#define SIGCHLD   17
./expected/wasm32-wasi/predefined-macros.txt:#define __WASI_SIGNAL_CHLD (UINT8_C(16))
./libc-bottom-half/headers/public/wasi/api.h:#define __WASI_SIGNAL_CHLD (UINT8_C(16))
```

**Comment by dkegel-fastly** [comment]
I mean, it's kind of moot since wasi doesn't really have signals, but still...

**Comment by sunfishcode** [comment]
I think the answer is 17. WebAssembly as a platform doesn't support signals, and isn't likely going to for the foreseeable future, so these constants will be defined by wasi-libc, which uses them for some amount of emulation, and not by the WASI spec itself.
