### ISSUE TITLE
README seems to be wrong wrt minimal LLVM version

### ISSUE THREAD

**Issue by msirringhaus** [WebAssembly/wasi-libc#301]
The README states it needs clang8+, but I tried building wasi-libc today with clang9, which did not compile because of missing attribute [export_name](https://releases.llvm.org/10.0.0/tools/clang/docs/AttributeReference.html#id233). That got added with clang10.
I don't know if clang10 would work or choke on something else, because I now switched to 14.
Still, I think the README should list the correct minimal LLVM version (whichever that may be).

**Comment by sbc100** [comment]
Aside from those attributes I don't think we depend on any particularly modern clang features in wasm-libc. 

Or you could just just update it to 10?  I'm not sure it worth the effort to add llvm 10 testing to the github CI but that would be best way to guarantee we do actually support LLVM 10.

**Comment by msirringhaus** [comment]
Sounds good. Nevertheless, I will look a bit into adding LLVM 10 to CI (maybe Linux only) tomorrow. Shouldn't be too bad, I think.
