### ISSUE TITLE
Is it safe to have mixed sbrk and malloc calls?

### ISSUE THREAD

**Issue by TerrorJack** [WebAssembly/wasi-libc#334]
Is it safe for a user module to do `sbrk` calls, both before and after the first `malloc` call that initializes the dlmalloc allocator state?

**Comment by TerrorJack** [comment]
Looks like it's unsafe to do `sbrk` before the first `malloc` call, otherwise the space claimed by `sbrk` will be incorrectly assumed to be usable space between `__heap_base` and end of linear memory.

As for `sbrk` calls after `dlmalloc` has been initialized, at least the comment related to `MORECORE_CONTIGUOUS` claims it's secure: https://github.com/WebAssembly/wasi-libc/blob/main/dlmalloc/src/malloc.c#L364

**Comment by sunfishcode** [comment]
That's my understanding as well.

Calling `sbrk` before the first `malloc` call could be made to work if we added a symbol to wasm-ld that marks the end of linear memory that it knows about, and then `try_init_allocator` could use that instead of `CALL_MORECORE(0)`.

**Comment by TerrorJack** [comment]
Thanks for the confirmation. It would be nice to document this somewhere, but for now hopefully google will lead people to this ticket.
