### ISSUE TITLE
libc.a is not built reproducibility/deterministically

### ISSUE THREAD

**Issue by PieroV** [WebAssembly/wasi-libc#398]
When building `libc.a` in different machines with identical configuration, I get a different results.
It seems that the problem is the order in which the archive is created (I see some `wildcard` in the `Makefile`, but adding `$(sort )` to them is not enough).

As a result, a Firefox with WASI sandbox cannot be built in  a [reproducible way](https://reproducible-builds.org/).
Reproducibility matters to several projects, like Debian or Tor Browser (disclosure: I am a Tor Browser developer).

As a workaround, I created a Python script to re-create `libc.a`, but I wonder if something can be done to create `libc.a` deterministically in the first place (maybe some tweaks to the `Makefile` are enough).

Please notice that extracting `libc.a` with `llvm-ar x libc.a` and then creating it again with a sorted input list does not work, because the archive currently contains two `errno.o`, and also some object files without a name.

**Comment by abrown** [comment]
I think it makes sense to attempt this; thanks for looking into it. Off the top of my head, I can't think of what the fix would be; you've tried the same standard things I would have tried. Perhaps posting more information about the differences would make things more clear? In any case, if you do figure out a fix, feel free to tag me in the review.

**Comment by PieroV** [comment]
I have tried again to try to give you more information.

This time I have set `$(sort)` both in the wildcards and in the `%.a` inputs.
Let me open a PR with my changes.
