### ISSUE TITLE
Please tag wasi-sdk-20

### ISSUE THREAD

**Issue by cuviper** [WebAssembly/wasi-libc#416]
Could you please add a tag corresponding to `wasi-sdk-20`? It looks like that submodule was at commit 1dfe5c302d1c5ab621f7abf04620fae92700fd22.

```
[wasi-sdk]$ git ls-tree wasi-sdk-20 src/wasi-libc
160000 commit 1dfe5c302d1c5ab621f7abf04620fae92700fd22  src/wasi-libc
```

**Comment by abrown** [comment]
Ok, done! See [tags](https://github.com/WebAssembly/wasi-libc/tags).

**Comment by cuviper** [comment]
Thanks!
