### ISSUE TITLE
Please tag wasi-sdk-21

### ISSUE THREAD

**Issue by cuviper** [WebAssembly/wasi-libc#461]
Can we get a tag for the new SDK release? Looks like it was at c5264e2bbe532994d06b039005f2af91bedcc1a6.

**Comment by abrown** [comment]
Ok, I confirmed that is the right commit and pushed the tag `wasi-sdk-21` for it. Can you check everything looks as expected on your end?

**Comment by cuviper** [comment]
Looks right, thanks!

However, I'm now reminded that #378 is outstanding. I had some suggested updates there, so I guess I'll try to submit a PR of my own...
