### ISSUE TITLE
both `/` and `.` preopens "normlaize" to empty string meaning it is not possible to preopen root and current dir simultaneously

### ISSUE THREAD

**Issue by mtobin-tdab** [WebAssembly/wasi-libc#484]
I have been directed here via [this issue](https://github.com/bytecodealliance/wasmtime/issues/8068) which describes being unable to preopen both `/` and `.` path simultaneously due to the fact that [they are both "normalized" to](https://github.com/WebAssembly/wasi-libc/blob/a1b4def387614c391276cc4b2d1f1bdb8994cf3e/libc-bottom-half/sources/preopens.c#L84-L102) to an empty string.

**Comment by yamt** [comment]
it seems that you are assuming the host cwd is somehow magically transferred to wasi. actually it isn't.
the relative path in your module is expected to be interpreted as it's relative to the wasi-emulated cwd, which is in your case "/" i guess.

**Comment by mtobin-tdab** [comment]
What do you mean magically transferred? I am assuming that by passing both `/` and `.` file descriptors I'm granting the program the capability to open files in both directories. Individually passed, each preopen behaves as expected. However, attempting to preopen both results in only one being successfully registered. To me this suggests a conflict or is this expected?

If so is there a way of registering both current directory and root as preopens so that my application can work with files using `./` and `/` references. 

Apologies if the question is ignorant, am new to web assembley and trying to understand.

**Comment by yamt** [comment]
> I am assuming that by passing both / and . file descriptors I'm granting the program the capability to open files in both directories.

consider that your "." is "/home/me" on the host.
if you run "wasmtime --dir=. -- yourapp.wasm foo", you expect yourapp.wasm will open "/home/me/foo" on host, right?
however, wasi doesn't really know the path of your ".".
actually, in wasi, your current directory is "/" unless you call chdir().
if yourapp.wasm opens "foo", which means "/foo" in wasi.

i guess you can make you app do chdir("cur-dir") on startup and
"wasmtime --dir=/ --dir=.::cur-dir yourapp.wasm" to get your expected result.

**Comment by mtobin-tdab** [comment]
Okay but the below does work (i.e. my app is able to read ./foo from host)

```bash
wasmtime --dir=. myapp.wasm ./foo 
```

So as I said either `--dir=/` or `--dir=.` work alone, but not at the same time, which seems like a bug to me.

**Comment by yamt** [comment]
> Okay but the below does work (i.e. my app is able to read ./foo from host)
> 
> ```shell
> wasmtime --dir=. myapp.wasm ./foo 
> ```

it isn't working as you seem expecting.
your current directory in wasi is "/".
so "./foo" is same as "/foo".

> So as I said either `--dir=/` or `--dir=.` work alone, but not at the same time, which seems like a bug to me.

you need to use different paths if you need to access both of them.
it isn't specific to ".".

**Comment by mtobin-tdab** [comment]
Alright thanks for you attention. Will close this now
