### ISSUE TITLE
httpclient module  for API request

### ISSUE THREAD

**Issue by hasinthajanaka** [WebAssembly/wasi-libc#503]
I am trying to develop a simple API request to get data in my Rust application. Still, I couldn't find the HTTP client wasm interface (wit file) for use in this. 

Could you provide the way to use HTTP client module with an example.

**Comment by abrown** [comment]
This is probably the wrong repository for that question; libc is operating at a lower level than what you're asking about. Maybe ask around on [Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/219900-wasi) or on the [wasi-http](https://github.com/WebAssembly/wasi-http) repository?
