### ISSUE TITLE
FTS Support

### ISSUE THREAD

**Issue by kateinoigakukun** [WebAssembly/wasi-libc#520]
wasi-libc does not include fts(3) implementation now, and it prevents us from reusing other platforms' code while porting [swift-foundation](https://github.com/apple/swift-foundation) to WASI.

Can we ship https://github.com/void-linux/musl-fts licensed under BSD 3-Clause as a part of wasi-libc?

The implementation is well-matured and well-used in the Alpine ecosystem. The only change we need to apply to the implementation is not to depend on `fchdir` by making `FTS_NOCHDIR` default.

**Comment by sbc100** [comment]
Since we already have some BSD-licensed parts of wasi-libc it doesn't seem unreasonable to me.  

Could we include it via a submodule and upstream the `FTS_NOCHDIR` mod you mention?
