### ISSUE TITLE
Missing tags for wasi-sdk 23 and 24

### ISSUE THREAD

**Issue by bjorn3** [WebAssembly/wasi-libc#547]

**Comment by cuviper** [comment]
Looking at the wasi-sdk submodules, those should be:
* wasi-sdk-23 3f43ea9abb24ed8d24d760989e1d87ea385f8eaa
  https://github.com/WebAssembly/wasi-sdk/tree/wasi-sdk-23/src
* wasi-sdk-24 b9ef79d7dbd47c6c5bafdae760823467c2f60b70
  https://github.com/WebAssembly/wasi-sdk/tree/wasi-sdk-24/src
